In [9]:
import numpy as np

arr = np.array([1,2,3,4,5])
print("tamaño del arreglo:", arr.size)

array = [1, 2, 3]
print("python tamaño del array:", len(array))

tamaño del arreglo: 5
python tamaño del array 3


In [7]:
arr = np.array([[1,2,3], 
                [4,5,6]])
print("forma del arreglo:", arr.shape) #2 filas, 3 columnas

forma del arreglo: (2, 3)


In [10]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [11]:
arr = np.array([1,2,3,4,5,6])
print("Consumo de memoria:", arr.nbytes, "bytes")

Consumo de memoria: 48 bytes


In [16]:
arr = np.array([1,2,3,4,5])
print("Tipo de datos del arreglo:", arr.dtype)

arr = np.array([1.1,2,3,4,5])#con un solo decimal todo el array se vuelve float por consistencia y todos tengan el mismo tipo de datos
print("Tipo de datos del arreglo:", arr.dtype)

Tipo de datos del arreglo: int64
Tipo de datos del arreglo: float64


In [27]:
#indexado unidimensional
arr = np.array([1,2,3])
print("elemento posicion 2:", arr[2])
print()

#indexado bidimensional
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr)
#arr[0][1] #2 #misma sintaxis
print("elemento en la posición (2,1):", arr[2,1])

elemento posicion 2: 3

[[1 2 3]
 [4 5 6]
 [7 8 9]]
elemento en la posición (2,1): 8


In [29]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr[-1] = 11
arr[2] = 0
print("arreglo modificado:", arr)

arreglo modificado: [ 1  2  0  4  5  6  7  8 11]


In [34]:
#slicing: indexado con rangos start:end:step,  end excluido
arr = np.array([1,2,3,4,5])
print("subarreglo:", arr[1:4])

arr1 = np.array([1,2,3,4,5,8,9,10])
print("subarreglo:", arr1[1:-1:2])

subarreglo: [2 3 4]
subarreglo: [2 4 8]


In [35]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
sub_arr = arr[0:2, 1:3]
print(sub_arr)
#np.random.randn(60, 1900, 1080)

[[2 3]
 [6 7]]


In [40]:
#obtener todas las filas de la tercera columna
sub_column = arr[:,2]
print(sub_column)

#ultimas dos filas y últimas dos columnas
sub_arr = arr[-2:, -2:]
print(sub_arr)

[ 3  7 11]
[[ 7  8]
 [11 12]]


In [43]:
#reshape(reformar): reacomodar o cambiar el tamaño de las matrices, o combinar matrices, alguna operacion u operacion
arr = np.array([1,2,3,4,5,6,7,8,9])
#cambiar la forma del arreglo a una matriz de 2 filas y 3 columnas
reshaped_arr = arr.reshape(3,3) #multiplicado debe dar el valor del array 3*3=9
print(reshaped_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
#cambiar la forma del arreglo a una matriz de  3 filas y tamaño de columnas en automatico
reshaped_arr = arr.reshape(3, -1)
print(reshaped_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [45]:
#reacomodar matrices ya existentes, ej arr bidimensional de 3*4
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
#cambiar forma a matriz de 2 * 6 columnas
reshaped_arr = arr.reshape(2,6)
print(reshaped_arr)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [46]:
#combinaciones de arrays: concatenate()
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
result = np.concatenate((arr1, arr2))
print(result)


[1 2 3 4 5 6]


In [48]:
#vstack: unir arreglos verticalmente
result = np.vstack((arr1, arr2))
print(result)

#hstack: unir arreglos horizontalmente
result = np.hstack((arr1, arr2))
print(result)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
