In [9]:
import numpy as np

arr = np.array([1,2,3,4,5])
print("tamaño del arreglo:", arr.size)

array = [1, 2, 3]
print("python tamaño del array:", len(array))

tamaño del arreglo: 5
python tamaño del array 3


In [7]:
arr = np.array([[1,2,3], 
                [4,5,6]])
print("forma del arreglo:", arr.shape) #2 filas, 3 columnas

forma del arreglo: (2, 3)


In [10]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [11]:
arr = np.array([1,2,3,4,5,6])
print("Consumo de memoria:", arr.nbytes, "bytes")

Consumo de memoria: 48 bytes


In [16]:
arr = np.array([1,2,3,4,5])
print("Tipo de datos del arreglo:", arr.dtype)

arr = np.array([1.1,2,3,4,5])#con un solo decimal todo el array se vuelve float por consistencia y todos tengan el mismo tipo de datos
print("Tipo de datos del arreglo:", arr.dtype)

Tipo de datos del arreglo: int64
Tipo de datos del arreglo: float64


In [27]:
#indexado unidimensional
arr = np.array([1,2,3])
print("elemento posicion 2:", arr[2])
print()

#indexado bidimensional
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr)
#arr[0][1] #2 #misma sintaxis
print("elemento en la posición (2,1):", arr[2,1])

elemento posicion 2: 3

[[1 2 3]
 [4 5 6]
 [7 8 9]]
elemento en la posición (2,1): 8


In [29]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr[-1] = 11
arr[2] = 0
print("arreglo modificado:", arr)

arreglo modificado: [ 1  2  0  4  5  6  7  8 11]


In [34]:
#slicing: indexado con rangos start:end:step,  end excluido
arr = np.array([1,2,3,4,5])
print("subarreglo:", arr[1:4])

arr1 = np.array([1,2,3,4,5,8,9,10])
print("subarreglo:", arr1[1:-1:2])

subarreglo: [2 3 4]
subarreglo: [2 4 8]


In [35]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
sub_arr = arr[0:2, 1:3]
print(sub_arr)
#np.random.randn(60, 1900, 1080)

[[2 3]
 [6 7]]


In [40]:
#obtener todas las filas de la tercera columna
sub_column = arr[:,2]
print(sub_column)

#ultimas dos filas y últimas dos columnas
sub_arr = arr[-2:, -2:]
print(sub_arr)

[ 3  7 11]
[[ 7  8]
 [11 12]]


In [43]:
#reshape(reformar): reacomodar o cambiar el tamaño de las matrices, o combinar matrices, alguna operacion u operacion
arr = np.array([1,2,3,4,5,6,7,8,9])
#cambiar la forma del arreglo a una matriz de 2 filas y 3 columnas
reshaped_arr = arr.reshape(3,3) #multiplicado debe dar el valor del array 3*3=9
print(reshaped_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
#cambiar la forma del arreglo a una matriz de  3 filas y tamaño de columnas en automatico
reshaped_arr = arr.reshape(3, -1)
print(reshaped_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [45]:
#reacomodar matrices ya existentes, ej arr bidimensional de 3*4
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
#cambiar forma a matriz de 2 * 6 columnas
reshaped_arr = arr.reshape(2,6)
print(reshaped_arr)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [46]:
#combinaciones de arrays: concatenate()
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
result = np.concatenate((arr1, arr2))
print(result)


[1 2 3 4 5 6]


In [48]:
#vstack: unir arreglos verticalmente
result = np.vstack((arr1, arr2))
print(result)

#hstack: unir arreglos horizontalmente
result = np.hstack((arr1, arr2))
print(result)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [25]:
import numpy as np
arr1 = np.array([1,2,3]).reshape(-1,1)#que tenga una columna
arr2 = np.array([4,5,6]).reshape(-1,1)
print(arr1)
print(arr2)
result= np.hstack((arr1, arr2))
print(result)


[[1]
 [2]
 [3]]
[[4]
 [5]
 [6]]
[[1 4]
 [2 5]
 [3 6]]


In [39]:
arr = np.array([1,2,3,4,5,6])
#dividir el arreglo en tres partes split()
result = np.split(arr,3)
print(result)
resh=arr.reshape(2,3)
print(resh)
resultv = np.vsplit(resh, 2)
print(resultv)
print()
resulth = np.hsplit(resh,3)
print(resulth)
#crear arreglo np vacio
#np.empty((10,4))#queda lleno de memoria basura

[array([1, 2]), array([3, 4]), array([5, 6])]
[[1 2 3]
 [4 5 6]]
[array([[1, 2, 3]]), array([[4, 5, 6]])]

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [53]:
#operaciones vectorizadas: operar sobre las matrices
#broadcasting
import numpy as np
#M = np.ones((3,3))
M = np.arange(9).reshape(3,3)
print(M)
a = np.array([0,1,2])
M + a

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [61]:
np.eye(4)
#np.zeros((8,3))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
import numpy as np
arr_s = np.array(['hello','como','estas']) #no es recomendable np arrays cadenas, no se puede operar adecuadamente
arr_s.dtype

arr_s

array(['hello', 'como', 'estas'], dtype='<U5')

In [9]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
#arr1.T.dot(arr2) #32 #trasponer
arr1@arr2

32

In [18]:
#repaso python
lista = []
"""
while len(lista) > 5:
     for i in range (1,5):
          lista.append(i);
print(lista) """
for i in range(5):
    lista.append(i)

for element in lista:
    print(element)

lista.append(5)
print(lista) 
print("*"*10)
contactos = {
    'a': '1',
    'b': '2',
    'c': '3',
}
#print(contactos[input("a,b,c")])
contactos['a']='0'
print(contactos)
for element in contactos:
    print(element)

0
1
2
3
4
[0, 1, 2, 3, 4, 5]
**********
{'a': '0', 'b': '2', 'c': '3'}
a
b
c


In [13]:
import numpy as np

# Supongamos que tienes el arreglo temperaturas
temperaturas = np.array([25, 30, 27, 22, 29, 31, 26, 28])

# Temperatura media
temperatura_media = np.mean(temperaturas)

# Diferencias deseadas
diferencias_deseadas = np.array([49.75, 58.75, 53.35, 44.35, 56.95, 60.55, 51.55, 55.15])

# Calcula las diferencias para obtener los valores deseados
diferencias = diferencias_deseadas - (temperaturas - temperatura_media)

print("Diferencias Deseadas:", diferencias_deseadas)
print("Diferencias Calculadas:", diferencias)


Diferencias Deseadas: [49.75 58.75 53.35 44.35 56.95 60.55 51.55 55.15]
Diferencias Calculadas: [52.  56.  53.6 49.6 55.2 56.8 52.8 54.4]
